create table
  stocks (
    id bigint generated by default as identity primary key,
    isin text,
    intl_symbol text,
    company_name text,
    price_snapshot float,
    ipo_date bigint,
    type_id text,
    exchange_id text,
    image_id text,
    distribution_frequency text,
    company_info_id int8 not null references company_infos,
    analyst_rating_id int8 not null references analyst_ratings,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
  );
