create table
  portfolios (
    id bigint generated by default as identity primary key,
    name text,
    user_id bigint references users,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
