create table
  sectors (
    id bigint generated by default as identity primary key,
    sector_id text unique,
    name text,
    icon text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
