create table
  portfolios (
    id bigint generated by default as identity primary key,
    name text,
    user_id int,
    foreign key (user_id) references users (id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
