create table
  dividends_fund (
    id bigint generated by default as identity primary key,
    isin text,
    ex_date_unix bigint,
    ex_date_iso text,
    record_date_iso text,
    record_date_unix bigint,
    payment_date_unix bigint,
    payment_date_iso text,
    amount float,
    fund_id bigint references funds,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
