create table
  funds (
    id bigint generated by default as identity primary key,
    isin text,
    fund_name text,
    description text,
    price_snapshot float,
    type_id text,
    exchange_id text,
    image_id text,
    distribution_frequency text,
    focus text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);
