create table
  orders (
    id bigint generated by default as identity primary key,
    order_id text,
    type text,
    amount_changed numeric,
    name text,
    price numeric,
    timestamp bigint,
    isin text,
    instrument_type text
  );
